// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apzgpshuzdbvjazzohii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwemdwc2h1emRidmphenpvaGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTMwNjAsImV4cCI6MjA3MjkyOTA2MH0.22rFWBhF8XPPfi2885X6EKhVDrZA0lfzF0WTpnHrQp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});